# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quotes • Library / yEAh Network
email: yeahgamesdevs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Host of the official yEAh Games quote collection for quotes of the day, quotes of the month, quotes of the year, etc. Readable and searchable at https://quotes.yeahgames.net. Library collections (https://library-collections.yeahgames.net) are a way to browse aggregated Archives content in a separate library designed for a certain purpose. 
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://3258xukj1pdvjerq7elfh19bc83mvzsi1bhozxox9thk7mscyvyyphud-secure.yeahgames.net" # the base hostname & protocol for your site

#sidebar
default-image: https://cdn.yeahgames.net/img/branding/logos/text/red.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: The yEAh Games Corporation, LLC. # For robot crawling & indexing

collection: # Details about your collection
   name: Quote Archive
   shortname: Quotes # The common, short name of your collection (1 word only)
   link: '//quotes.yeahgames.net' # The link to your collection's website

owner: # Details about your collection's owner(s)/management
   name: The yEAh Archiving Team
   link: '//archiveteam.yeahgames.net'

copyright: # Copyright details
   name: The yEAh Games Corporation, LLC.
   link: 'https://yeahgames.net'

# Build settings
permalink: /posts/:title/ #NOTE: CHANGE TO /ITEM EVENTUALLY, ONCE A SERVER-SIDE REDIRECT SLOT HAS BEEN FREED
paginate: 9
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: no
disqus-shortname: webjeda-demo

#social
facebook:
quora:
twitter: http://twitter.com/yEAhGames_
github: http://github.com/yEAh-Games
email: admin@yeahgames.net
mastodon: https://mstdn.social/@yeah
instagram: https://instagram.com/_yeahgames

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

